apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: adewaleijalana/posts
          resources:
            requests:
              memory: '32Mi'
              cpu: '100m'
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: posts-service
spec:
  type: ClusterIP
  selector:
    app: posts
  ports:
    - port: 4000
      name: posts
      protocol: TCP
      targetPort: 4000
